#!/usr/bin/php
<?php

require __DIR__.'/src/Arguments.php';
require __DIR__.'/src/DescriptionFile.php';
require __DIR__.'/src/TypeMapping.php';
require __DIR__.'/src/CsvParser.php';

$arguments = Arguments::parse($argv);
if ($arguments->hasParsingErrors()) {
    echo 'Errors during arguments parsing :'.PHP_EOL;
    foreach ($arguments->getParsingErrors() as $error) {
        echo "  - {$error}".PHP_EOL;
    }
}

$description = DescriptionFile::parse($arguments->getDescriptionFilePath());


$csvParser = CsvParser::initFromFilePath($arguments->getCsvFilePath());
foreach($csvParser->getIterator() as $line => $data) {
    var_dump($line);
    var_dump($data);
}

exit(0);