#!/usr/bin/php
<?php

require __DIR__.'/src/autoload.php';

$arguments = Csv2Json\Arguments::parse($argv);
if ($arguments->hasParsingErrors()) {
    echo 'Errors during arguments parsing :'.PHP_EOL;
    foreach ($arguments->getParsingErrors() as $error) {
        echo "  - {$error}".PHP_EOL;
    }
}

$description = Csv2Json\DescriptionFile::parse($arguments->getDescriptionFilePath());


$csvParser = Csv2Json\CsvParser::initFromFilePath($arguments->getCsvFilePath());
foreach($csvParser->getIterator() as $line => $data) {
    var_dump($line);
    var_dump($data);
}

exit(0);